### ISSUE TITLE
Wrong sample values with a certain ogg

### ISSUE THREAD

**Issue by hajimehoshi** [jfreymuth/oggvorbis#2]
I found that https://raw.githubusercontent.com/hajimehoshi/go-inovation/master/ino/internal/assets/resources/sound/ino1.ogg causes noise with oggvorbis. Note that before fixing #1, there were sample values exceeding e.g. 10 in that audio file when decoding with jfreymuth/oggvorbis. I've confirmed that there wasn't noise with Firefox ogg player or others. Thanks.

**Comment by jfreymuth** [comment]
should be fixed by jfreymuth/vorbis@9581977ccb17fb56daf09c4ff11699ce7f18712c

**Comment by hajimehoshi** [comment]
Awesome. That worked perfectly. Thank you!
