### ISSUE TITLE
Some OGG files don't seem to decode or play correctly

### ISSUE THREAD

**Issue by Keithcat1** [jfreymuth/oggvorbis#5]
I'm using "github.com/faiface/beep" to play audio, which in turn uses this library to decode OGG Vorbis files.
But some OGG files play at a much higher pitch and speed than they should.
I attached a zip file with a script that plays the sound, and a .ogg file that doesn't play correctly.
Help would be appreciated!
Here is the zip.
[test.zip](https://github.com/jfreymuth/oggvorbis/files/3998618/test.zip)

**Comment by jfreymuth** [comment]
This seems to be a bug in [github.com/faiface/beep](https://github.com/faiface/beep). Your file only contains one channel while beep always assumes two channels without actually checking the format.

**Comment by jfreymuth** [comment]
(As far as I can tell, the offending line is
https://github.com/faiface/beep/blob/b573886bdf0f6ac1b8e7f8931a2a2b249c90666b/vorbis/decode.go#L34)
