### ISSUE TITLE
better error messsage when an empty stream is passed

### ISSUE THREAD

**Issue by hajimehoshi** [jfreymuth/oggvorbis#9]
```go
package main

import (
        "bytes"
        "fmt"

        "github.com/jfreymuth/oggvorbis"
)

func main() {
        if _, err := oggvorbis.NewReader(bytes.NewReader(nil)); err != nil {
                fmt.Println(err)
        }
}
```

Now `NewReader` just returns `io.EOF`. Would it be possible to return a more meaningful error for this case?

**Comment by jfreymuth** [comment]
I've changed the error in this case to `io.UnexpectedEOF`
If there is nothing else I will tag another version.

**Comment by hajimehoshi** [comment]
Thanks, this is all of my request.
